config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  root to: 'home#index'

  get 'home/show' => 'home#show', as: :home_show
  resources :questions
  resources :users_answers
  resources :users
end

app/models/question.rb
class Question < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: [:slugged, :finders]

  mount_uploader :image, ImageUploader

  has_many :answers
  has_many :users_answers
  belongs_to :category
  belongs_to :level
  belongs_to :user

  after_save :set_image_original_url
  after_save :initalize_point_for_user

  accepts_nested_attributes_for :answers, allow_destroy: true, :reject_if => lambda { |a| a[:content].blank? && a[:label].blank? }

  # scope :correct_answer, -> (question_id) { find(question_id).answers.corrected }
  validates :title, length: {minimum: 10, maximum: 200}
  validates :content, length: {minimum: 5}

  def correct_answer
  	answers.find_by(correct: true)
  end

  private

  def set_image_original_url
    update_column(:image_original_url, image_url)
  end

  def initalize_point_for_user
    update(points: 5, remain_points: 5) if points.to_i == 0
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, only: [:new, :create, :edit, :update]
  
  def index
    # @q = Product.search(params[:q])
    # @products = @q.result.includes(:product_images).order(updated_at: :desc).page(params[:page]).per(12)
    # @related_products = Product.includes(:product_images).related_products
    # @top_viewed_products = Product.includes(:product_images).top_viewed_products_except(@product)
    # @top_new_products = Product.includes(:product_images).top_new_products
    redirect_to root_path
  end

  def show
    Question.update_counters(@question.id, count_views: 1)
    # @q = Product.search(params[:q])
    # CountView.increase_product_count(@product.id, current_user.try(:id))
    # @related_products = Product.includes(:product_images).related_products
    # @top_viewed_products = Product.includes(:product_images).top_viewed_products_except(@product)
    # @top_new_products = Product.includes(:product_images).top_new_products
    # @top_campaign_products = Product.includes(:product_images).top_campaign_products(3)
  end

  def new
    @question = Question.new(title: params[:title])
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = @question.updated_user_id = current_user.id
    @question.slug = chang_to_slug(@question.title)
    respond_to do |format|
      if @question.save
        format.html { redirect_to question_path(@question.slug), notice: 'question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @question.attributes = question_params
    @question.updated_user_id = current_user.id
    @question.slug = chang_to_slug(@question.title)
    respond_to do |format|
      if @question.save
        format.html { redirect_to question_path(@question.slug), notice: 'question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.friendly.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:level_id, :video_url, :image, :remove_image, :category_id, :title, :difficulty_level, :content, :hint, answers_attributes: [:id, :correct, :question_id, :label, :content, :image, :_destroy])
    end
end

app/views/questions/_answer_fields.html.erb
<% if f.object.new_record? %>
  <% ['A', 'B', 'C', 'D'].each_with_index  do |label, i|%>
    <div class="poll_options" style="display: block;">
    <%= f.hidden_field :question_type, value: 'poll'%>
    <%= f.fields_for :answers, answer, child_index: id + i do |att| %>
      <%= att.hidden_field :user_id, value: 1 %>
      <%= att.hidden_field :label, value: label %>
      <%= att.hidden_field :_destroy, class: 'destroy_element' %>
        <ul class="question_poll_item question_polls_item ui-sortable">
          <li id="poll_li_5" style="display: block; background-color: #f2eaea;">
            <div class="poll-li" style="display: block; background-color: #f2eaea;">
            <p><%= att.text_field :label, value: label, placeholder: t('views.answers.answer_label'), class: 'label-text1'%></p>
            <span class="del-poll-li remove_fields"><%= link_to "<i class='fa fa-remove'>".html_safe, "javascript:void(0)", class: "btn btn-danger btn-mini" %></i></span>
              <p><%= att.text_field :content, placeholder: "Noi dung Phuong an #{label}" %></p>
              <span><%= att.check_box :correct, checked: answer.correct, class: 'question_poll' %> <%= t('views.answers.correct_answer')%></span>
              <span><%= att.file_field :image %></span>
              <% if answer && answer.image? %>
                <span><%= link_to answer.image_url, answer.image_url  %></span>
                <div><img src="<%= answer.image_url %>" class='img-list-product' /></div>
              <% end %>
            </div>
          </li>
        </ul>
        <div class="clearfix"></div>
    <% end %>
    </div>
  <% end %>
<% else %>
  <div class="poll_options" style="display: inline-block;">
  <%= f.fields_for :answers, answer, child_index: id do |att| %>
    <%= att.hidden_field :user_id, value: 1 %>
    <%= att.hidden_field :label, value: answer.label || 'A' %>
    <%= att.hidden_field :_destroy, class: 'destroy_element' %>
      <ul class="question_poll_item question_polls_item ui-sortable">
        <li id="poll_li_5" style="display: inline-block; background-color: #f2eaea;">
          <p><%= att.text_field :label, placeholder: t('views.answers.answer_label'), size: '100' %></p>
          <div class="poll-li">
            <p><%= att.text_field :content, placeholder: "Noi dung Phuong an #{answer.label}" %></p>
            <div class="del-poll-li remove_fields"><%= link_to "<i class='fa fa-remove'>".html_safe, "javascript:void(0)", class: "btn btn-danger btn-mini" %></i></div>
            <span><%= att.check_box :correct, checked: answer.correct, class: 'question_poll' %> <%= t('views.answers.correct_answer')%></span>
            <span><%= att.file_field :image %></span>
            <% if answer && answer.image? %>
              <span><%= link_to answer.image_url, answer.image_url  %></span>
              <div><img src="<%= answer.image_url %>" class='img-list-product' /></div>
            <% end %>
          </div>
        </li>
      </ul>
      <div class="clearfix"></div>
  <% end %>
  </div>
<% end %>

app/views/questions/_attachment_field.html.erb
<%= f.file_field :image, class: 'file attachment_file'%>
<%= f.hidden_field :remove_image, id: 'remove_image' %>

<span class="fakefile">
  <button type="button" class="button small margin_0"><%= t('views.common.select_file')%></button>
  <span><i class="icon-arrow-up"></i>Browse</span>
</span>

app/views/questions/_form.html.erb
<div class="form-posts">
  <div class="form-style form-style-3 question-submit">
    <div class="ask_question">
      <div>
        <%= form_for(@question) do |f| %>
          <div class=""><%= render partial: "errors", locals: { object: @question } %></div>

          <div class="form-inputs clearfix">
            <p>
              <label class="required"><%= h_model(f, :title) %><span>*</span></label>
              <%= f.text_field :title, class: 'the-title' %>
              <span class="form-description">Hãy chọn tiêu đề ngắn ngọn và dễ hiểu !^^</span>
            </p>

            <p>
              <label class="required"><%= h_model(f, :category_id) %><span>*</span></label>
              <span class="styled-select">
              <%= f.collection_select :category_id, Category.all, :id, :name, selected: @question.category_id, class: 'postform' %>
              </span>
            </p>

            <p>
              <label class="required"><%= h_model(f, :content) %><span>*</span></label>
              <%= f.text_area :content, class: 'the-title the-textarea' %>
            </p>

            <p>
              <label class=""><%= h_model(f, :video_url) %></label>
              <input type="checkbox" class="video_question" <%=@question.video_url.present? ? 'checked' : ''%> /> Đăng video mô tả cho câu hỏi
              <br/>
              <%= f.text_field :video_url, class: 'the-title video_field', placeholder: 'Link youtube hoac facebook video', style: "display: #{@question.video_url.present? ? '' : 'none'};" %>
            </p>

            <p>
              <label class=""><%= h_model(f, :image) %></label>
              <input type="checkbox" class="image_question" <%= @question.image_url.present? ? 'checked' : ''%> /> Đăng ảnh mô tả cho câu hỏi
              <span class="fileinputs" style="display: <%= @question.image_url.present? ? '' : 'none'%>">
                <%= render partial: 'attachment_field', locals: {f: f} %>
                <img src="<%= @question.image_url(:simple) %>">
              </span>
            </p>

            <p>
              <label><%= h_model f, :hint %></label>
              <%= f.text_area :hint, class: 'the-title the-textarea' %>
            </p>

            <p>
              <label class="required"><%= h_model f, :level_id %><span>*</span></label>
              <span class="styled-select">
              <%= f.collection_select :level_id, Level.all, :id, :name, selected: @question.level_id, class: 'postform' %>
              </span>
            </p>

            <p>
              <label class="required"><%= h_model f, :difficulty_level %><span>*</span></label>
              <span class="styled-select">
              <%= f.select :difficulty_level, Settings.questions.difficulty_level.map{|level| [t("views.answers.difficulty_level.#{level}"), level]}, selected: @question.difficulty_level, class: 'postform' %>
              </span>
            </p>

            <p class="question_poll_p" id="input_attachments">
              <label for="question_poll-298"><%= h_model f, :poll %></label>
              <% unless @question.new_record? %>
                <% @question.answers && @question.answers.each_with_index do |answer, i| %>
                  <%= render "answer_fields", {answer: answer, f: f, id: i} %>
                <% end %>
                <%= link_to_add_attachment t(:button_add_answer, scope: [:views, :labels]), f, :answers, {append_id: "input_attachments", table_id: " link_to_add_attachment", class: "btn btn-warning btn-mini" } %>
              <% else %>
                <span class="question_poll">Đây là một câu hỏi trác nghiệm?</span>
                <span class="poll-description"> Click vào đây .</span>
                <%= link_to_add_attachment t(:button_add_answer, scope: [:views, :labels]), f, :answers, {append_id: "input_attachments", table_id: " link_to_add_attachment", class: "btn-warning btn-mini" } %>
              <% end %>
            </p>
          </div>

          <div class="center">
            <% button = @question.new_record? ? :button_create : :button_edit %>
            <p class="form-submit">
              <%= f.submit t(button, scope: [:views, :labels]), class:"button color small submit add_qu publish-question", id: "button_submit" %>
            </p>
            <%= link_to t(:button_cancel, scope: [:views, :labels]), questions_path, class:"btn btn-danger button color small submit add_qu publish-question center" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/questions/_related_questions.html.erb
<div id="related-posts">
  <h2><%= t('views.questions.related_questions')%></h2>
  <ul class="related-posts">
    <%Question.all.each do |question|%>
    <li class="related-item">
      <h3><a href="<%= question_path(question) %>" title="<%= question.title %>"><i class="fa fa-double-angle-right"></i>
      <span class="btn btn-success"><span> <%= (10..100).to_a.sample %></span></span>
      <%= question.title %></a></h3>
    </li>
    <% end %>
  </ul>
</div>

app/views/questions/edit.html.erb
<%# render 'partials/breadcrumbs', breadcrumbs: ['products', 'add_new']%>
<section class="container main-content page-right-sidebar">
  <div class="row">
    <div class="with-sidebar-container">
      <div class="col-md-9">
        <div class="page-content">
          <div class="boxedtitle page-title">
            <h2>Edit Question</h2>
          </div>
          <%= render 'form' %>
        </div>     
      </div>
    </div>
    <%= render 'partials/sidebar' %>
    <div class="clearfix"></div>
  </div>
</section>

app/views/questions/new.html.erb
<%# render 'partials/breadcrumbs', breadcrumbs: ['products', 'add_new']%>
<div class="content">
  <div class="container">
    <div class="content-top">
      <div class="content-top1">
        <div class="clearfix"> </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>    
</div>

app/views/questions/show.html.erb
<% title (@question.title) %>
<section class="container main-content page-right-sidebar">
  <div class="row">
    <div class="with-sidebar-container">
      <div class="col-md-9">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <article class="question single-question question-type-poll post-266 type-question status-publish hentry question-category-wordpress question_tags-themes" id="post-266" role="article" itemtype="http://schema.org/Article">
          <h2 itemprop="name"><%= @question.title %></h2>
          <a class="question-report report_q" href="#"><%= t('views.button.report')%></a>
          <div class="question-type-main"><i class="icon-signal"></i>Poll</div>
          <div class="question-inner">
            <div class="clearfix"></div>
            <div class="question-desc" itemprop="mainContentOfPage">
              <div class="explain-reported">
                <h3><%= t('views.answers.report_reason')%></h3>
                <textarea name="explain-reported"></textarea>
                <div class="clearfix"></div>
                <div class="loader_3"></div>
                <div class="color button small report">Report</div>
                <div class="color button small dark_button cancel">Cancel</div>
              </div>
              <!-- End reported -->

              <% if @question.video_url.present? %>
                <h3>Nội dung câu hỏi trong video</h3>
              <div class="post-img video_embed post-img-9">
                <iframe height="450" src="https://www.youtube.com/embed/<%= youtube_id(@question.video_url) %>"></iframe>
              </div>
              <%end%>

              <% if @question.image_url %>
                <h3>Nội dung câu hỏi trong ảnh</h3>
                <div>
                  <img src="<%= @question.image_url %>" title="<%= @question.title%>" alt="<%= @question.title%>">
                </div>
                <br />
              <% end %>
              <div class="question_poll_end" style="display: none">
                <%= render partial: 'partials/progressbar_warp', locals: {question: @question} %>
              </div>
              <div class="open_stat btn btn-info">Xem thống kê <i class="fa fa-chevron-down"></i></div>
              <!-- End question_poll_end -->
              <div class="clearfix height_20"></div>
              <h4><%= @question.content %></h4><br>
                <%= form_for @question.users_answers.build, remote: true, authenticity_token: true, format: :js do |f| %>
                  <% @question.answers.each do |answer| %>
                    <div class="checkbox checkbox-primary">
                        <%= f.hidden_field :question_id, value: @question.id%>
                        <%= f.radio_button :answer, answer.id %>
                        <%= answer.label %>: <%= answer.content %>
                    </div>

                  <% end %>
                  <%= f.submit t('views.button.answer'), id: 'button-submit-question-show', class: 'center'%>
                <% end %>
              </p>
              <div class="loader_2"></div>
              <div class="no_vote_more"></div>
            </div>
            <div class="question-details">
              <span class="question-answered"><i class="fa fa-ok"></i>in progress</span>
              <span class="question-favorite"><i class="fa fa-star"></i><%= @question.remain_points%></span>
            </div>
            <span class="question-category"><a href="http://2code.info/demo/themes/ask-me/question-category/wordpress/"><i class="fa fa-folder-o"></i><%= "#{@question.category.name}"%> - <%= "#{@question.level.name}"  %></a></span>
            <span class="question-date" datetime="July 18, 2014"><i class="fa fa-calendar"></i>
            <%= distance_of_time_in_words_to_now(@question.updated_at)%> <%= t('views.common.ago')%></span>
            <span class="question-comment"><a href="http://2code.info/demo/themes/ask-me/questions/ask-any-question-and-you-be-sure-find-your-answer-2/#comments"><i class="fa fa-comments-o"></i><%= @question.users_answers.count %></a></span>
            <meta itemprop="interactionCount" content="UserAnswers: 59">
            <span class="question-view"><i class="fa fa-eye"></i><%= @question.count_views %></span>
            <span class="badge-span" style="background-color: #000000"><%= t("views.answers.difficulty_level.#{@question.difficulty_level}") if @question.difficulty_level %></span><span class="single-question-vote-result question_vote_result"><%= @question.count_likes %></span>
            <ul class="single-question-vote">
              <li><a href="#" class="single-question-vote-down ask_vote_down question_vote_down vote_not_user tooltip_s" original-title="Dislike"><i class="fa fa-thumbs-down"></i></a></li>
              <li><a href="#" class="single-question-vote-up ask_vote_up question_vote_up vote_not_user tooltip_s" original-title="Like"><i class="fa fa-thumbs-up"></i></a></li>
            </ul>
            <div class="clearfix"></div>
          </div>
        </article>
        <div class="share-tags page-content">
          <div class="question-tags"><i class="icon-tags"></i><a href="http://2code.info/demo/themes/ask-me/question-tag/themes/">themes</a></div>
          <div class="share-inside-warp">
            <ul>
              <li>
                <a href="http://www.facebook.com/sharer.php?u=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F" target="_blank">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#3b5997" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(59, 89, 151);">
                <i i_color="#FFF" class="social_icon-facebook" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a href="http://www.facebook.com/sharer.php?u=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F" target="_blank">Facebook</a>
              </li>
              <li>
                <a href="http://twitter.com/home?status=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F" target="_blank">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#00baf0" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(0, 186, 240);">
                <i i_color="#FFF" class="social_icon-twitter" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a target="_blank" href="http://twitter.com/home?status=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F">Twitter</a>
              </li>
              <li>
                <a href="http://plus.google.com/share?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F" target="_blank">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#ca2c24" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(202, 44, 36);">
                <i i_color="#FFF" class="social_icon-gplus" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a href="http://plus.google.com/share?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F" target="_blank">Google plus</a>
              </li>
              <li>
                <a href="http://www.tumblr.com/share/link?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F&amp;name=Ask+any+question+and+you+be+sure+find+your+answer+%3F" target="_blank">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#44546b" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(68, 84, 107);">
                <i i_color="#FFF" class="social_icon-tumblr" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a href="http://www.tumblr.com/share/link?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F&amp;name=Ask+any+question+and+you+be+sure+find+your+answer+%3F" target="_blank">Tumblr</a>
              </li>
              <li>
                <a target="_blank" href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F&amp;media=">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#c7151a" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(199, 21, 26);">
                <i i_color="#FFF" class="icon-pinterest" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2F2code.info%2Fdemo%2Fthemes%2Fask-me%2Fquestions%2Fask-any-question-and-you-be-sure-find-your-answer-2%2F&amp;media=" target="_blank">Pinterest</a>
              </li>
              <li>
                <a target="_blank" onclick="popup = window.open('mailto:?subject=Ask any question and you be sure find your answer ?&amp;body=http://2code.info/demo/themes/ask-me/questions/ask-any-question-and-you-be-sure-find-your-answer-2/', 'PopupPage', 'height=450,width=500,scrollbars=yes,resizable=yes'); return false" href="#">
                <span class="icon_i">
                <span class="icon_square" icon_size="20" span_bg="#000" span_hover="#666" style="height: 20px; width: 20px; font-size: 10px; line-height: 20px; border-style: solid; background-color: rgb(0, 0, 0);">
                <i i_color="#FFF" class="social_icon-email" style="color: rgb(255, 255, 255);"></i>
                </span>
                </span>
                </a>
                <a target="_blank" onclick="popup = window.open('mailto:?subject=Ask any question and you be sure find your answer ?&amp;body=http://2code.info/demo/themes/ask-me/questions/ask-any-question-and-you-be-sure-find-your-answer-2/', 'PopupPage', 'height=450,width=500,scrollbars=yes,resizable=yes'); return false" href="#">Email</a>
              </li>
            </ul>
            <span class="share-inside-f-arrow"></span>
            <span class="share-inside-l-arrow"></span>
          </div>
          <!-- End share-inside-warp -->
          <div class="share-inside"><i class="icon-share-alt"></i>Share</div>
          <div class="clearfix"></div>
        </div>
        <!-- End share-tags -->
        <div class="about-author clearfix">
          <div class="author-image">
            <a href="<%=user_path @question.user.uid %>" original-title="<%= @question.user.name %>" class="tooltip-n">
            <img alt="" src="<%= @question.user.avatar %>" srcset="<%= @question.user.avatar %>" class="avatar avatar-65 photo" height="65" width="65">                   </a>
          </div>
          <div class="author-bio">
            <h4>
              <%= t('models.questions.create_user')%> <a href="<%=user_path @question.user.uid %>"><%= @question.user.name%></a><span class="badge-span" style="background-color: #000000">Beginner</span>                      
            </h4>
            <div class="clearfix"></div>
          </div>
        </div>
        <!-- End about-author -->

        <%= render 'related_questions' %>
        <!-- End related-posts -->

        <%# render 'comments'%>

        <div class="pagination comments-pagination">
        </div>
        <!-- End comments-pagination -->
        <div id="respond" class="comment-respond page-content clearfix ">
          <div class="boxedtitle page-title">
            <h2>Leave an answer</h2>
          </div>
          <div class="fb-comments" data-href="<%= question_url(@question) %>" data-numposts="5"></div>
          <!-- <p class="no-login-comment">You must <a href="http://2code.info/demo/themes/ask-me/login/" class="login-comments">login</a> or <a href="http://2code.info/demo/themes/ask-me/login/" class="signup">register</a> to add a new answer .</p> -->
        </div>
        <div class="post-next-prev clearfix">
          <p class="prev-post">
            <a href="http://2code.info/demo/themes/ask-me/questions/como-va-todo/" rel="prev"><i class="icon-double-angle-left"></i>&nbsp;Previous question</a>               
          </p>
          <p class="next-post">
          </p>
        </div>
        <!-- End post-next-prev -->
      </div>
      <!-- End main -->
      <%= render 'partials/sidebar' %>
      <!-- End sidebar -->
      <div class="clearfix"></div>
    </div>
    <!-- End with-sidebar-container -->
  </div>
  <!-- End row -->
</section>