config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  root to: 'home#index'

  get 'home/show' => 'home#show', as: :home_show
  resources :questions
  resources :users_answers
  resources :users
end

app/views/partials/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <section class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>User Questions</h1>
        <div class="clearfix"></div>
        <div class="crumbs">
          <a itemprop="breadcrumb" href="http://2code.info/demo/themes/ask-me">Home</a><span class="crumbs-span">/</span> <span class="current">User Questions</span>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/partials/_progressbar_warp.html.erb
<h4><%= t('views.answers.stat')%></h4>
<div class="poll_2">
  <div class="progressbar-warp">
  <% question.answers.each do |answer| %>
    <span class="progressbar-title"><b><%= t('views.answers.answer') + " " + answer.label %></b> - <%= ratio_answer(question, answer.id) %><span>( <%= total_this_answer(question, answer.id)%>/<%= total_answers(question) %> )</span></span>
    <div class="progressbar">
      <div class="progressbar-percent " style="width: <%=ratio_answer(question, answer.id).to_s%>; background-color: rgb(52, 152, 219);" attr-percent="<%= ratio_answer(@question, answer.id)%>"></div>
    </div>
  <% end %>
  </div>
  <!-- End progressbar-warp -->
</div>
<div class="clear"></div>
<div class="poll_2">
  <div class="loader_3"></div>
  <div class="form-style form-style-3">
    <div class="form-inputs clearfix">
    </div>
  </div>
</div>

app/views/partials/_sidebar.html.erb
<aside class="col-md-3 sidebar sticky-sidebar" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">
  <div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static;">
    <div class="widget_ask">
      <a href="<%= new_question_path %>" class="color button small margin_0">Ask a Question</a>
    </div>
    <% if current_user %>
      <%= render 'partials/sidebars/user_infor' %>
    <% else %>
      <%= render 'partials/sidebars/login_widget'%>
    <% end %>    

    <%= render 'partials/sidebars/stat'%>
    <%= render 'partials/sidebars/social_network' %>

    <%= render 'partials/sidebars/highest_point' %>

    <% render 'partials/sidebars/tags' %>
    <%= render 'partials/sidebars/recent_questions'%>
  </div>
</aside>
<!-- End sidebar -->

app/views/partials/_stat.html.erb
<div id="stats-widget-2" class="widget stats-widget">
  <h3 class="widget_title">Stats</h3>
  <div class="widget_stats ul_list ul_list-icon-ok">
    <ul>
      <li><i class="icon-question-sign"></i>Questions ( <span><%= Question.count %></span> )</li>
      <li><i class="fa fa-comments-o"></i>Answers ( <span><%= UsersAnswer.count %></span> )</li>
      <!-- <li><i class="fa fa-comments-o"></i>Best Answers ( <span>8</span> )</li> -->
      <li><i class="icon-user"></i>Users ( <span><%= User.count %></span> )</li>
    </ul>
  </div>
</div>