config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  root to: 'home#index'

  get 'home/show' => 'home#show', as: :home_show
  resources :questions
  resources :users_answers
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(updated_at: :desc)
  end

  def show
  	@question = Question.last
  end
end

app/views/home/index.html.erb
  <% title ('Cộng đồng hỏi và trả lời các câu hỏi cho học sinh, sinh viên') %>
  <section class="container main-content page-right-sidebar">
    <div class="row">
      <div class="with-sidebar-container">
        <div class="col-md-9">
          <div class="tabs-warp question-tab">
            <ul class="tabs">
              <li class="tab"><a href="#" data-js="recent_questions" class="current">Recent Questions</a></li>
              <li class="tab"><a href="#" data-js="most_responses">Most Responses</a></li>
              <li class="tab"><a href="#" data-js="recently_answered">Recently Answered</a></li>
              <li class="tab"><a href="#" data-js="no_answers">No answers</a></li>
              <li class="tab"><a href="#" data-js="recent_posts">Recent Posts</a></li>
            </ul>
            <div class="tab-inner-warp" style="display: block;">
              <div class="tab-inner">
                <% @questions.each do |question| %>
                <article class="question question-type-poll question_author_yes post-266 type-question status-publish hentry question-category-wordpress question_tags-themes" id="post-266" role="article" itemtype="http://schema.org/Article">
                  <h2 itemprop="name">
                    <a itemprop="url" href="<%= question_path(question.slug || question) %>" title="<%= question.title %>" rel="bookmark"><%= question.title %></a>
                  </h2>
                  <a class="question-report report_q" href="#"><%= t('views.button.report')%></a>
                  <div class="question-type-main"><i class="icon-signal"></i>Poll</div>
                  <div class="question-author">
                    <a href="<%= user_path(question.user.uid)%>" original-title="<%= question.user.name %>" class="question-author-img tooltip-n">
                    <span></span>
                    <img alt="" src="<%= question.user.avatar %>" srcset="<%= question.user.avatar %>" class="avatar avatar-65 photo" height="65" width="65"></a>
                  </div>
                  <div class="question-inner">
                    <div class="clearfix"></div>
                    <div class="question-desc">
                      <%= question.content %>
                      <br />
                      <% if question.video_url.present? %>
                      <div class="post-img video_embed post-img-9">
                        <iframe height="450" src="https://www.youtube.com/embed/<%= youtube_id(question.video_url) %>"></iframe>
                      </div>
                      <%end%>

                      <% if question.image_url %>
                        <div>
                          <img src="<%= question.image_url %>" title="<%= question.title%>" alt="<%= question.title%>">
                        </div>
                        <br />
                      <% end %>
                      <div class="explain-reported">
                        <h3><%= t('views.answers.report_reason')%></h3>
                        <textarea name="explain-reported"></textarea>
                        <div class="clearfix"></div>
                        <div class="loader_3"></div>
                        <div class="color button small report"><%= t('views.button.report')%></div>
                        <div class="color button small dark_button cancel"><%= t('views.button.cancel')%></div>
                      </div>
                      <!-- End reported -->
                      <div class="no_vote_more"></div>
                    </div>
                    <div class="question-details">
                      <span class="question-answered"><i class="fa fa-ok"></i>in progress</span>
                      <span class="question-favorite"><i class="fa fa-star"></i><%= question.remain_points%></span>
                    </div>
                    <span class="question-category"><a href="http://2code.info/demo/themes/ask-me/question-category/wordpress/"><i class="fa fa-folder-o"></i><%= "#{question.category.name}"%> - <%= "#{question.level.name}"  %></a></span>
                    <span class="question-date" datetime="July 18, 2014"><i class="fa fa-calendar"></i><%= distance_of_time_in_words_to_now(question.updated_at)%> <%= t('views.common.ago')%></span>
                    <span class="question-comment"><a href="http://2code.info/demo/themes/ask-me/questions/ask-any-question-and-you-be-sure-find-your-answer-2/#comments"><i class="fa fa-comments-o"></i>59 Answer</a></span>
                    <meta itemprop="interactionCount" content="UserAnswers: 59">
                    <span class="question-view"><i class="fa fa-eye"></i>25385 views</span>
                    <span class="badge-span" style="background-color: #000000"><%= t("views.answers.difficulty_level.#{question.difficulty_level}") if question.difficulty_level %></span>      
                    <div class="clearfix"></div>
                  </div>
                </article>

                <% if [true, false].sample %>
                  <div class="clearfix"></div>
                  <div class="advertising"><a target="_blank" href="#"><img alt="" src="http://2code.info/demo/themes/ask-me/wp-content/uploads/2014/07/adv728x90.gif"></a></div>
                  <!-- End advertising -->
                <% end %>
                <% end %>
              </div>
            </div>

            <div class="tab-inner-warp" style="display: none;">
              <div class="tab-inner">
                <div class="page-content page-content-user">
                  <p class="no-item">No Questions Found.</p>
                </div>
              </div>
            </div>

            <% render 'partials/other_posts' %>
          </div>
          <!-- End tabs-warp -->
        </div>
        <!-- End main -->
        <%= render 'partials/sidebar' %>
        <div class="clearfix"></div>
      </div>
      <!-- End with-sidebar-container -->
    </div> 
    <!-- End row -->
  </section>
  <!-- End container -->
<!-- End wrap -->