config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  root to: 'home#index'

  get 'home/show' => 'home#show', as: :home_show
  resources :questions
  resources :users_answers
  resources :users
end

app/views/partials/sidebars/_highest_point.html.erb
<div id="highest-points-widget-2" class="widget highest-points-widget">
  <h3 class="widget_title">Highest points</h3>
  <div class="widget_highest_points">
    <ul>
      <li>
        <div class="author-img">
          <a href="http://2code.info/demo/themes/ask-me/author/ask-me/">
          <img alt="Ahmed Hassan" src="http://2code.info/demo/themes/ask-me/wp-content/uploads/2014/06/chefs-1-65x65.png">                  </a>
        </div>
        <div class="author-content">
          <h6><a href="http://2code.info/demo/themes/ask-me/author/ask-me/">Ahmed Hassan</a></h6>
          <span class="badge-span" style="background-color: #dd9933">Pundit</span>                  <span class="comment">183 Points</span>
        </div>
        <div class="clearfix"></div>
      </li>
      <li>
        <div class="author-img">
          <a href="http://2code.info/demo/themes/ask-me/author/user/">
          <img alt="" src="http://0.gravatar.com/avatar/38017e24b7012687d0ca168c8f9afd12?s=65&amp;d=mm&amp;r=g" srcset="http://0.gravatar.com/avatar/38017e24b7012687d0ca168c8f9afd12?s=130&amp;d=mm&amp;r=g 2x" class="avatar avatar-65 photo" height="65" width="65">                 </a>
        </div>
        <div class="author-content">
          <h6><a href="http://2code.info/demo/themes/ask-me/author/user/">user</a></h6>
          <span class="badge-span" style="background-color: #dd9933">Pundit</span>                  <span class="comment">163 Points</span>
        </div>
        <div class="clearfix"></div>
      </li>
      <li>
        <div class="author-img">
          <a href="http://2code.info/demo/themes/ask-me/author/350929070/">
          <img alt="350929070" src="http://2code.info/demo/themes/ask-me/wp-content/uploads/2016/09/us-65x65.jpg">                  </a>
        </div>
        <div class="author-content">
          <h6><a href="http://2code.info/demo/themes/ask-me/author/350929070/">350929070</a></h6>
          <span class="badge-span" style="background-color: #000000">Beginner</span>                  <span class="comment">49 Points</span>
        </div>
        <div class="clearfix"></div>
      </li>
      <li>
        <div class="author-img">
          <a href="http://2code.info/demo/themes/ask-me/author/sachin119/">
          <img alt="" src="http://0.gravatar.com/avatar/0b58c8ebaaf8823a7b8c9e32dff558fd?s=65&amp;d=mm&amp;r=g" srcset="http://0.gravatar.com/avatar/0b58c8ebaaf8823a7b8c9e32dff558fd?s=130&amp;d=mm&amp;r=g 2x" class="avatar avatar-65 photo" height="65" width="65">                 </a>
        </div>
        <div class="author-content">
          <h6><a href="http://2code.info/demo/themes/ask-me/author/sachin119/">sachin119</a></h6>
          <span class="badge-span" style="background-color: #000000">Beginner</span>                  <span class="comment">46 Points</span>
        </div>
        <div class="clearfix"></div>
      </li>
      <li>
        <div class="author-img">
          <a href="http://2code.info/demo/themes/ask-me/author/denis/">
          <img alt="denis" src="http://2code.info/demo/themes/ask-me/wp-content/uploads/2016/05/Dragan-Nikolic-copy-620x350-65x65.jpg">                 </a>
        </div>
        <div class="author-content">
          <h6><a href="http://2code.info/demo/themes/ask-me/author/denis/">denis</a></h6>
          <span class="badge-span" style="background-color: #000000">Beginner</span>                  <span class="comment">43 Points</span>
        </div>
        <div class="clearfix"></div>
      </li>
    </ul>
  </div>
</div>

app/views/partials/sidebars/_login_widget.html.erb
<div id="login-widget-2" class="widget login-widget">
  <h3 class="widget_title">Login</h3>
  <div class="widget_login">

  <ul class="widget_social">
    <li class="facebook-fans">
      <a href="/auth/facebook">
      <strong>
      <i class="social_icon-facebook"></i>
      <!-- <span>436</span><br> -->
      <span>Login via</span>
      <small>Facebook </small>
      </strong>
      </a>
    </li>

  </ul>
  <br>
   <div class="center" style="background-color: #aea28f">OR</div> 
    <div class="form-style form-style-2">
      <div class="ask_form inputs">
        <form class="login-form ask_login" action="http://2code.info/demo/themes/ask-me/" method="post">
          <div class="ask_error"></div>
          <div class="form-inputs clearfix">
            <p class="login-text">
              <input class="required-item" type="text" value="Username" onfocus="if (this.value == 'Username') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Username';}" name="log">
              <i class="icon-user"></i>
            </p>
            <p class="login-password">
              <input class="required-item" type="password" value="Password" onfocus="if (this.value == 'Password') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Password';}" name="pwd">
              <i class="icon-lock"></i>
              <a href="#">Forget</a>
            </p>
          </div>
          <p class="form-submit login-submit">
            <span class="loader_2"></span>
            <input type="submit" value="Log in" class="button color small login-submit submit sidebar_submit">
          </p>
          <div class="rememberme">
            <label><input type="checkbox" input="" name="rememberme" checked="checked"> Remember Me</label>
          </div>
          <input type="hidden" name="redirect_to" value="http://2code.info/demo/themes/ask-me/">
          <input type="hidden" name="login_nonce" value="dd0ba90ee8">
          <input type="hidden" name="ajax_url" value="http://2code.info/demo/themes/ask-me/wp-admin/admin-ajax.php">
          <input type="hidden" name="form_type" value="ask-login">
          <div class="errorlogin"></div>
        </form>
      </div>
      <ul class="login-links login-links-r">
        <li><a href="#">Register</a></li>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/partials/sidebars/_recent_questions.html.erb
<div id="questions-widget-2" class="widget questions-widget">
  <h3 class="widget_title">Recent Questions</h3>
  <ul class="related-posts">
    <li class="related-item">
      <div class="questions-div">
        <h3>
          <a href="http://2code.info/demo/themes/ask-me/questions/ask-any-question-and-you-be-sure-find-your-answer-2/" title="Ask any question and you be sure find your answer ?" rel="bookmark">
          Ask any question and you              </a>
        </h3>
        <p>Hi,
          My name is Bao. I’m from VietNam. I love WordPress and ...
        </p>
        <div class="clear"></div>
        <span>July 18 , 2014</span>
      </div>
    </li>
    <li class="related-item">
      <div class="questions-div">
        <h3>
          <a href="http://2code.info/demo/themes/ask-me/questions/como-va-todo/" title="como va todo?" rel="bookmark">
          como va todo?             </a>
        </h3>
        <p>queria saber como esta todo?
          ...
        </p>
        <div class="clear"></div>
        <span>July 6 , 2014</span>
      </div>
    </li>
    <li class="related-item">
      <div class="questions-div">
        <h3>
          <a href="http://2code.info/demo/themes/ask-me/questions/example-question/" title="Example Question" rel="bookmark">
          Example Question              </a>
        </h3>
        <p>Example detail.
          ...
        </p>
        <div class="clear"></div>
        <span>July 6 , 2014</span>
      </div>
    </li>
  </ul>
</div>

app/views/partials/sidebars/_social_network.html.erb
<div id="counter-widget-2" class="widget counter-widget">
  <h3 class="widget_title">Find Us</h3>
  <ul class="widget_social">
    <li class="rss-subscribers">
      <a href="http://2code.info/demo/themes/ask-me/feed/" target="_blank">
      <strong>
      <i class="icon-rss"></i>
      <span>Subscribe</span><br>
      <small>To RSS Feed</small>
      </strong>
      </a>
    </li>
    <li class="facebook-fans">
      <a href="https://www.facebook.com/2code.info/" target="_blank">
      <strong>
      <i class="social_icon-facebook"></i>
      <span>436</span><br>
      <small>People like it</small>
      </strong>
      </a>
    </li>
    <li class="gplus-subs">
      <a href="https://plus.google.com/+envato" target="_blank">
      <strong>
      <i class="icon-google-plus"></i>
      <span>13,592</span><br>
      <small>Followers</small>
      </strong>
      </a>
    </li>
    <li class="twitter-followers">
      <a href="http://twitter.com/envato" target="_blank">
      <strong>
      <i class="social_icon-twitter"></i>
      <span>62,112</span><br>
      <small>Followers</small>
      </strong>
      </a>
    </li>
    <li class="youtube-subs">
      <a href="http://www.youtube.com/channel/UCht9cayN2rRaXk5VgMJtAsA" target="_blank">
      <strong>
      <i class="icon-play"></i>
      <span>451</span><br>
      <small>Subscribers</small>
      </strong>
      </a>
    </li>
  </ul>
</div>

app/views/partials/sidebars/_tags.html.erb
<div id="tag_cloud-2" class="widget widget_tag_cloud">
  <h3 class="widget_title">Tags</h3>
  <div class="tagcloud"><a href="http://2code.info/demo/themes/ask-me/question-tag/answer/" class="tag-link-18 tag-link-position-1" title="1 topic" style="font-size: 8pt;">Answer</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/data/" class="tag-link-35 tag-link-position-2" title="1 topic" style="font-size: 8pt;">data</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/egypt/" class="tag-link-27 tag-link-position-3" title="1 topic" style="font-size: 8pt;">Egypt</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/first/" class="tag-link-13 tag-link-position-4" title="1 topic" style="font-size: 8pt;">First</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/glasses/" class="tag-link-30 tag-link-position-5" title="1 topic" style="font-size: 8pt;">glasses</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/joomla/" class="tag-link-16 tag-link-position-6" title="1 topic" style="font-size: 8pt;">joomla</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/lorem/" class="tag-link-33 tag-link-position-7" title="1 topic" style="font-size: 8pt;">lorem</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/museum/" class="tag-link-26 tag-link-position-8" title="1 topic" style="font-size: 8pt;">Museum</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/no/" class="tag-link-17 tag-link-position-9" title="1 topic" style="font-size: 8pt;">No</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/normal/" class="tag-link-14 tag-link-position-10" title="1 topic" style="font-size: 8pt;">Normal</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/problem/" class="tag-link-15 tag-link-position-11" title="1 topic" style="font-size: 8pt;">Problem</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/pyramids/" class="tag-link-28 tag-link-position-12" title="1 topic" style="font-size: 8pt;">Pyramids</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/question/" class="tag-link-12 tag-link-position-13" title="2 topics" style="font-size: 13.25pt;">Question</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/sample/" class="tag-link-34 tag-link-position-14" title="1 topic" style="font-size: 8pt;">sample</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/themes/" class="tag-link-67 tag-link-position-15" title="1 topic" style="font-size: 8pt;">themes</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/uhtv/" class="tag-link-41 tag-link-position-16" title="1 topic" style="font-size: 8pt;">uhtv</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/web/" class="tag-link-29 tag-link-position-17" title="1 topic" style="font-size: 8pt;">web</a>
    <a href="http://2code.info/demo/themes/ask-me/question-tag/wordpress/" class="tag-link-457 tag-link-position-18" title="5 topics" style="font-size: 22pt;">WordPress</a>
  </div>
</div>

app/views/partials/sidebars/_user_infor.html.erb
<div id="login-widget-2" class="widget login-widget">
  <h3 class="widget_title">Your's profile</h3>
  <div class="widget_login">
    <ul>
      <li>
        <div class="author-img">
          <a href="<%= user_path(current_user)%>">
          <img alt="<%= current_user.name %>" src="<%= current_user.avatar %>">                  </a>
        </div>
        <div class="author-content">
          <h6><a href="<%= user_path(current_user)%>"><%= current_user.name %></a></h6>
          <span class="badge-span" style="background-color: #dd9933"><%= current_user.type %></span><span class="comment"><%= current_user.points.to_i %> <%=t('models.users.points')%></span>
        </div>
        <div class="clearfix"></div>
      </li>
      <li><i class="fa fa-envelope"></i> <%= current_user.email %></li>
      <li><i class="fa fa-archive"></i> <%= current_user.type || 'Beginer'%></li>
      <li><i class="fa fa-bar-chart"></i> <%= current_user.level.try(:name) || '0' %></li>
      <li><i class="fa fa-star"></i> <%= current_user.points.to_i %> <%=t('models.users.points')%></li>
      <li><i class="fa fa-sign-out"></i> <%= link_to "Sign out", signout_path, id: "sign_out" %></li>
    </ul>
  </div>
  <div class="clearfix"></div>
</div>